---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: nsx-ujo-docker-local.artifactory.eng.vmware.com/ncp-ci/ncp-ci-image
    tag: ubuntu18-v1

inputs:
  - name: nsx-t-gen-pipeline
  - name: nsxt-ansible
  - name: ovftool

run:
  path: nsx-t-gen-pipeline/tasks/install-nsx-t/task.sh
