---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: nsx-ujo-docker-local.artifactory.eng.vmware.com/nsx-t-gen-worker
    tag: testv6

inputs:
  - name: nsx-t-gen-pipeline
  - name: nsxt-ansible
  - name: ovftool

run:
  path: nsx-t-gen-pipeline/tasks/install-nsx-t/task.sh
