---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: nsx-ujo-docker-local.artifactory.eng.vmware.com/ncp-ci/ncp-ci-image
    tag: ubuntu18-v1

# params:
#   VCENTER_HOST:
#   VCENTER_USR:
#   VCENTER_PWD:


inputs:
  - name: nsx-t-gen-pipeline

run:
  path: nsx-t-gen-pipeline/tasks/uninstall-nsx-t/task.sh

